### ISSUE TITLE
use of state files .UUID_STATE not documented

### ISSUE THREAD

**Issue by nicolasfranck** [bleargh45/Data-UUID#33]

**Comment by phochste** [comment]
When the state file or .UUID_NODEID is corrupted for any reason the Data::UUID package will hang. On my system already two types I had an issue where all my services were stalled until one or both of these files were deleted an regenerated.

**Comment by bleargh45** [comment]
With #44 merged (a re-submission of #40), this issue is no longer relevant; the `.UUID_*` state/node files are no longer used.
